server:
  port: 8094
  servlet:    context-path: /
spring:  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.70.1:3306/baobeidb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root

#mybatis-plush配置
mybatis-plus:  type-aliases-package: com.bb.pojo
  mapper-locations: classpath:/mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true  
#引入日志信息
logging:
  level: 
    com.jt.mapper: debug 

dubbo:
  scan:
    basePackages: com.bb
  application:
    name: provider-cart   #定义服务名称
  registry:               #定义注册中心链接
    address: zookeeper://192.168.70.129:2181?backup=192.168.70.129:2182,192.168.70.129:2183
  protocol:
    name: dubbo     #变量名称一般固定
    port: 20881     #生产者端口号